**Numeryczne rozwiązywanie równań różniczkowych**\
Łukasz Jarzęcki 331697

In [49]:
import numpy as np
import re
from scipy.io import loadmat
import time
import matplotlib.pyplot as plt


1. **Implementacje metod**

1.1 **Metoda Eulera**

In [50]:
def euler_base(x0, y0, h0, f_par, iters):
    x = x0
    y = y0
    h = h0
    f = f_par

    x_vec = np.zeros(iters)
    y_vec = np.zeros(iters)
    x_vec[0] = x
    y_vec[0] = y


    for i in range(1, iters):
        y = y+h*f(x,y)
        x = x+h
        x_vec[i] = x
        y_vec[i] = y
        #print(f"{i}: x: {x}\t y: {y}")

    return x_vec, y_vec


x,y = euler_base(1,0.5,0.1, lambda x,y: 3*x*y**2, 5)
print(x)
print(y)

[1.  1.1 1.2 1.3 1.4]
[0.5        0.575      0.68410625 0.85258674 1.13607936]


1.2 **Zmodyfikowana metoda Eulera**

In [51]:
def euler_mod(x0, y0, h0, f_par, iters):
    x = x0
    y = y0
    h = h0
    f = f_par

    x_vec = np.zeros(iters)
    y_vec = np.zeros(iters)
    x_vec[0] = x
    y_vec[0] = y

    for i in range(1, iters):
        y = y+h*f(x+0.5*h,y+0.5*h*f(x,y))
        x = x+h
        x_vec[i] = x
        y_vec[i] = y
        #print(f"{i}: x: {x}\t y: {y}")

    return x_vec, y_vec

x,y = euler_mod(1,0.5,0.1, lambda x,y: 3*x*y**2, 5)
print(x)
print(y)

[1.  1.1 1.2 1.3 1.4]
[0.5        0.59100547 0.73615771 0.99680658 1.57087001]


1.3 **Metoda Rungego-Kutty**

In [52]:
def runge_kutty(x0, y0, h0, f_par, iters):
    x = x0
    y = y0
    h = h0
    f = f_par

    x_vec = np.zeros(iters)
    y_vec = np.zeros(iters)
    x_vec[0] = x
    y_vec[0] = y

    K1 = lambda x,y: f(x,y)
    K2 = lambda x,y: f(x+0.5*h, y+0.5*h*K1(x,y))
    K3 = lambda x,y: f(x+0.5*h, y+0.5*h*K2(x,y))
    K4 = lambda x,y: f(x+0.5*h, y+0.5*h*K3(x,y))

    for i in range(1, iters):
        y = y + (h/6)*(K1(x,y) + 2*K2(x,y)+2*K3(x,y) + K4(x,y))
        x = x+h
        x_vec[i] = x
        y_vec[i] = y
        #print(f"{i}: x: {x}\t y: {y}")

    return x_vec, y_vec

x,y = runge_kutty(1,0.5,0.1, lambda x,y: 3*x*y**2, 5)
print(x)
print(y)

[1.  1.1 1.2 1.3 1.4]
[0.5        0.58978123 0.73293872 0.99163859 1.5819282 ]


1.4 **Metoda Heuna**

In [53]:
def heun(x0, y0, h0, f_par, iters):
    x = x0
    y = y0
    h = h0
    f = f_par

    x_vec = np.zeros(iters)
    y_vec = np.zeros(iters)
    x_vec[0] = x
    y_vec[0] = y

    for i in range(1, iters):
        y = y + 0.5*h* (f(x,y) + f(x+h,y+h*f(x,y)))
        x = x+h

        x_vec[i] = x
        y_vec[i] = y
        #print(f"{i}: x: {x}\t y: {y}")

    return x_vec, y_vec

x,y = heun(1,0.5,0.1, lambda x,y: 3*x*y**2, 5)
print(x)
print(y)

[1.  1.1 1.2 1.3 1.4]
[0.5        0.59205312 0.74004802 1.00990937 1.6249196 ]


2. **Analiza powyższych metod numerycznych**

In [55]:
f = lambda x,y: (4*x)/((1+x**2)**(1/3))